sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - ./Build.sh
  - docker tag "blutner/ocomis-info:latest" "blutner/ocomis-info:$TRAVIS_COMMIT"
  - docker push "blutner/ocomis-info:$TRAVIS_COMMIT"
  - docker push "blutner/ocomis-info:latest"
  - docker logout
