sudo: required

language: node_js

services:
  - docker

before_install:
  - docker build -t blutner/ocomis-info:latest .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push blutner/ocomis-info:latest
  - docker logout
